apiVersion: v2
name: galaxy
type: application
version: 4.0.0-rc.1
appVersion: "21.01"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
